inertia_parameters:
  link0_mass: 2.66011637
  link1_mass: 21.79610064
  link2_mass: 12.60732858
  link3_mass: 4.23106394
  link4_mass: 4.38018787
  link5_mass: 3.34480372
  link6_mass: 1.17565610

  link0:
    ixx: 0.01927017
    iyy: 0.01958893
    izz: 0.02237911
    ixy: 0.00000209
    iyz: -0.00000161
    ixz: -0.00018510

  link1:
    ixx: 0.64644592
    iyy: 0.57818705
    izz: 0.11837303
    ixy: -0.00003372
    iyz: -0.18649956
    ixz: 0.00009653

  link2:
    ixx: 0.13229838
    iyy: 3.23685598
    izz: 3.15391475
    ixy: 0.00076742
    iyz: 0.00006199
    ixz: 0.26489776

  link3:
    ixx: 0.21380764
    iyy: 0.05312553
    izz: 0.17094678
    ixy: 0.00008360
    iyz: 0.07683268
    ixz: 0.00004813

  link4:
    ixx: 0.26334164
    iyy: 0.23849973
    izz: 0.03312887
    ixy: 0.00002727
    iyz: -0.06989898
    ixz: -0.00008141

  link5:
    ixx: 0.06379181
    iyy: 0.02330575
    izz: 0.04532227
    ixy: 0.00000349
    iyz: -0.02607468
    ixz: -0.00000426

  link6:
    ixx: 0.01197125
    iyy: 0.01231621
    izz: 0.00623213
    ixy: -0.00004800
    iyz: 0.00006597
    ixz: -0.00060569

  center_of_mass:
    link0:
      x: -0.00097315
      y: -0.00001067
      z: 0.04283787
    link1:
      x: -0.00000317
      y: -0.03899639
      z: 0.12657986
    link2:
      x: 0.43289670
      y: 0.00009936
      z: 0.06604965
    link3:
      x: -0.00008637
      y: -0.16831579
      z: -0.09969111
    link4:
      x: -0.00009292
      y: -0.05782084
      z: 0.20600122
    link5:
      x: -0.00001242
      y: -0.09704958
      z: 0.07235011
    link6:
      x: 0.00085635
      y: -0.00030276
      z: 0.03417689

