inertia_parameters:
  link0_mass: 2.56262283
  link1_mass: 23.04941339
  link2_mass: 13.86898329
  link3_mass: 4.33211778
  link4_mass: 5.29001581
  link5_mass: 3.54429783
  link6_mass: 3.63235920

  link0:
    ixx: 0.01579442
    iyy: 0.01654858
    izz: 0.02120350
    ixy: 0.00001182
    iyz: -0.00000167
    ixz: -0.00035039

  link1:
    ixx: 1.07131491
    iyy: 0.97571980
    izz: 0.15642641
    ixy: -0.00088608
    iyz: -0.27757611
    ixz: 0.00373079

  link2:
    ixx: 0.13467172
    iyy: 3.33493355
    izz: 3.25250492
    ixy: -0.00000279
    iyz: -0.00000626
    ixz: 0.21911594

  link3:
    ixx: 0.12705385
    iyy: 0.05350425
    izz: 0.08353879
    ixy: -0.00007126 
    iyz: 0.05251141
    ixz: -0.00005316

  link4:
    ixx: 0.49421792
    iyy: 0.47039115
    izz: 0.03440872
    ixy: 0.00000967
    iyz: -0.09570180
    ixz: -0.00006517

  link5:
    ixx: 0.03025870
    iyy: 0.02534867
    izz: 0.01049163
    ixy: -0.00000921
    iyz: -0.00570954
    ixz: 0.00004266

  link6:
    ixx: 0.02296417
    iyy: 0.02294874
    izz: 0.01036532
    ixy: -0.00000053
    iyz: 0.00075929
    ixz: 0.00095428
    
  center_of_mass:
    link0:
      x: -0.00258732
      y: 0.00000000
      z: 0.03670771
    link1:
      x: 0.00091757
      y: -0.04560974
      z: 0.17670678
    link2:
      x: 0.41245408
      y: -0.00000145
      z: 0.05902447
    link3:
      x: 0.00010688
      y: -0.11279641
      z: -0.09952194
    link4:
      x: -0.00003298
      y: -0.05026763
      z: 0.26334634
    link5:
      x: 0.00014570
      y: -0.02035115
      z: 0.07381123
    link6:
      x: -0.00362661
      y: -0.00287313
      z: -0.00146223
      