joint_limits:
  joint0:
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_velocity: 3
    max_acceleration: 3
    max_effort: 60.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint1:
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_velocity: 3
    max_acceleration: 3
    max_effort: 50.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint2:
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_velocity: 3
    max_acceleration: 3
    max_effort: 40.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint3:
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_velocity: 3
    max_acceleration: 3
    max_effort: 30.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint4:
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_velocity: 3
    max_acceleration: 3
    max_effort: 20.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint5:
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: true
    has_effort_limits: true
    max_velocity: 3
    max_acceleration: 3
    max_effort: 10.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0