inertia_parameters:
  link0_mass: 1.66957888
  link1_mass: 11.43955917
  link2_mass: 6.11383823
  link3_mass: 2.68211719
  link4_mass: 2.12830848
  link5_mass: 2.32413397
  link6_mass: 0.39652271

  link0:
    ixx: 0.00655829
    iyy: 0.00639165
    izz: 0.00791712
    ixy: 0.00000183
    iyz: -0.00000027
    ixz: 0.00002634

  link1:
    ixx: 0.35097123
    iyy: 0.30435880
    izz: 0.06048047
    ixy: 0.00013006
    iyz: -0.11072619
    ixz: -0.00042705

  link2:
    ixx: 0.74655601
    iyy: 0.03850444
    izz: 0.72200046
    ixy: -0.00032714
    iyz: 0.05314531
    ixz: 0.00000481

  link3:
    ixx: 0.11373278
    iyy: 0.01627234
    izz: 0.10021441
    ixy: -0.00003686
    iyz: 0.03355709
    ixz: -0.00001286

  link4:
    ixx: 0.02795227
    iyy: 0.01439850
    izz: 0.01495514
    ixy: 0.00003938
    iyz: -0.01265087
    ixz: -0.00004713

  link5:
    ixx: 0.01771876
    iyy: 0.01593616
    izz: 0.00358348
    ixy: 0.00000904
    iyz: -0.00069656
    ixz: -0.00004336

  link6:
    ixx: 0.00077839
    iyy: 0.00076561
    izz: 0.00051275
    ixy: 0.00000026
    iyz: -0.00000699
    ixz: 0.00000000

  center_of_mass:
    link0:
      x: 0.00133032
      y: -0.00000218
      z: 0.03163661
    link1:
      x: -0.00027386
      y: -0.04348767
      z: 0.13216705
    link2:
      x: -0.00010864
      y: 0.29071865
      z: 0.04588251
    link3:
      x: 0.00006691
      y: -0.16802208
      z: -0.07025671
    link4:
      x: -0.00026808
      y: -0.07105971
      z: 0.07645329
    link5:
      x: -0.00022538
      y: -0.00354123
      z: 0.07650762
    link6:
      x: 0.00000000
      y: -0.00071501
      z: 0.03219123