# How links connect together
kinematics:
  joint0:
    x: 0
    y: 0
    z: 0.0775
    roll: 0
    pitch: 0
    yaw: 0
  joint1:
    x: 0
    y: -0.109
    z: 0.222
    roll: 1.570796327
    pitch: 1.570796327
    yaw: 0
  joint2:
    x: -0.45
    y: 0
    z: -0.0305
    roll: 0
    pitch: 0
    yaw: 0
  joint3:
    x: -0.267
    y: 0
    z: -0.075
    roll: -1.570796327
    pitch: 0
    yaw: 1.570796327
  joint4:
    x: 0
    y: -0.114
    z: +0.083
    roll: 1.570796327
    pitch: 1.570796327
    yaw: 0
  joint5:
    x: -0.168
    y: 0
    z: 0.069
    roll: -1.570796327
    pitch: 0
    yaw: 1.570796327
