inertia_parameters:
  link0_mass: 1.59306955
  link1_mass: 11.80301028
  link2_mass: 7.99292141
  link3_mass: 2.99134127
  link4_mass: 2.12317035
  link5_mass: 2.28865091
  link6_mass: 0.40083918

  link0:
    ixx: 0.00572623
    iyy: 0.00558959 
    izz: 0.00966674 
    ixy: 0.00000251 
    iyz: -0.00000014 
    ixz: -0.00011380

  link1:
    ixx: 0.15418559
    iyy: 0.12937017
    izz: 0.05964415
    ixy: 0.00000235
    iyz: -0.04854267 
    ixz: 0.00001739

  link2:
    ixx: 0.29362989
    iyy: 0.28094142 
    izz: 0.03620609 
    ixy: -0.00000040
    iyz: 0.03728952 
    ixz: 0.00001441

  link3:
    ixx: 0.03427124
    iyy: 0.03408518
    izz: 0.00450709
    ixy: 0.00000141 
    iyz: 0.00185907
    ixz: 0.00000743

  link4:
    ixx: 0.00672334
    iyy: 0.00279246
    izz: 0.00619341
    ixy: 0.00000390 
    iyz: -0.00128342
    ixz: 0.00000146

  link5:
    ixx: 0.00996598
    iyy: 0.00979853 
    izz: 0.00272125 
    ixy: 0.00000004
    iyz: -0.00093616
    ixz: 0.00000331

  link6:
    ixx: 0.00043534
    iyy: 0.00044549
    izz: 0.00059634
    ixy: 0.00000013
    iyz: 0.00000051
    ixz: -0.00000002