inertia_parameters:
  link0_mass: 1.6703078
  link1_mass: 11.44444535
  link2_mass: 4.43308185
  link3_mass: 2.87045928
  link4_mass: 2.68206064
  link5_mass: 2.12987371 
  link6_mass: 2.22412271
  link7_mass: 0.38254932
#
  link0:
    ixx: 0.00661309
    iyy: 0.00644765
    izz: 0.00792090 
    ixy: 0.00000183 
    iyz: -0.00000027 
    ixz: 0.00002695

  link1:
    ixx: 0.35065005
    iyy: 0.30479800
    izz: 0.06003147
    ixy: 0.00011931
    iyz: -0.10984447
    ixz: -0.00037553

  link2:
    ixx: 0.03742681
    iyy: 0.32119654
    izz: 0.29396155
    ixy: 0.00003176
    iyz: -0.00000808
    ixz: -0.07906734

  link3:
    ixx: 0.04098160
    iyy: 0.02106773
    izz: 0.02277477
    ixy: 0.00000747
    iyz: 0.01817157
    ixz: 0.00000916

  link4:
    ixx: 0.01617210
    iyy: 0.11364055
    izz: 0.10022522
    ixy: -0.00011817 
    iyz: -0.00004371
    ixz: 0.03341882

  link5:
    ixx: 0.02798891
    iyy: 0.01443076
    izz: 0.01496211
    ixy: 0.00003893
    iyz: -0.01266296
    ixz: -0.00004768

  link6:
    ixx: 0.01105297
    iyy: 0.03698291 
    izz: 0.02754795
    ixy: 0.00005517
    iyz: -0.00003740
    ixz: -0.01481977

  link7:
    ixx: 0.00078982
    iyy: 0.00079764
    izz: 0.00058319
    ixy: -0.00000034
    iyz: -0.00000508
    ixz: 0.00000083

  center_of_mass:
    link0:
      x: 0.00131966
      y: -0.00000218
      z:  0.03212832
    link1:
      x: -0.00023749
      y: -0.04310313
      z: 0.13245396
    link2:
      x: -0.21209188
      y: -0.00001715
      z: 0.07901191
    link3:
      x: 0.00003637
      y: 0.07143055
      z: 0.07746050
    link4:
      x: -0.16804016
      y: 0.00021421
      z: -0.07000383
    link5:
      x: -0.00026847
      y: -0.07098440
      z: 0.07649128
    link6:
      x: -0.09796232
      y: -0.00023114
      z: 0.06445892
    link7:
      x: 0.00008147
      y: -0.00046556
      z: 0.03079097
      