6dof:
  joint0: 0.0
  joint1: 0.0
  joint2: -1.57
  joint3: 0.0
  joint4: -1.57
  joint5: 0.0
7dof:
  joint0: 0.0
  joint1: 0.0
  joint2: 0.0
  joint3: -1.57
  joint4: 0.0
  joint5: -1.57
  joint6: 0.0